spring:
  datasource:
    url: jdbc:mysql://cx:13306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: meiyoumima.0
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:oracle:thin:@192.168.242.17:1521:orcl
#    username: right
#    password: ffffff
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 50
  liquibase:
    change-log: classpath:/db/changelog/m1-onlineform-changelog.xml  # 默认设置 db.changelog-master.yaml
logging:
  level:
    "com.example.log4j2test.web.controller": debug
    "org.springframework": debug
