### 获取所有指标
GET http://localhost:25840/actuator

### 获取健康状况
GET http://localhost:25840/actuator/health

### 获取指标
GET http://localhost:25840/actuator/metrics

### 获取指标值
GET http://localhost:25840/actuator/metrics/cache.eviction.weight

### 获取prometheus指标
http://localhost:25840/actuator/prometheus

### 获取prometheus具体指标
http://localhost:25840/actuator/prometheus

### demo.jsp
http://localhost:25840/demo.jsp