
spring:
  datasource:
    url: jdbc:p6spy:mysql://cx:13306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: meiyoumima.0
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 50
logging:
  level:
    "com.example.log4j2test.web.controller": debug
server:
  port: 8081
