spring:
  application:
    name: factoryDemo
logging:
  level:
    com.example.factory: debug
    'org.springframework': trace
server:
  port: 8081

m1:
  server:
    title: 123456
    customize:
      testEnabled: true
      str: hello

